# Generated by Django 6.0.5 on 2026-05-12 02:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('full_name', models.CharField(max_length=200)),
                ('relationship', models.CharField(choices=[('father', 'Отец'), ('mother', 'Мать'), ('brother', 'Брат'), ('sister', 'Сестра'), ('grandfather', 'Дедушка'), ('grandmother', 'Бабушка'), ('guardian', 'Опекун'), ('other', 'Другое')], max_length=20)),
                ('phone_number', models.CharField(max_length=14)),
                ('is_primary', models.BooleanField(default=False)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='students.student')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
