# Generated by Django 6.0.5 on 2026-05-11 03:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('full_name', models.CharField(max_length=255)),
                ('inn', models.CharField(max_length=15, unique=True)),
                ('id_card', models.CharField(max_length=15, unique=True)),
                ('phone_number', models.CharField(max_length=12)),
                ('status', models.CharField(choices=[('active', 'Учится'), ('academic', 'Академ'), ('expelled', 'Отчислен')], default='active', max_length=20)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='students', to='academics.group')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
